---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ 24 * 60 * 60 }}"
  tags:
    - shell

- name: Install shellcheck
  apt:
    name: shellcheck
  tags:
    - shell

- name: Download shellcheck binary
  get_url:
    url: "{{ shell_linter_url }}"
    dest: "{{ shell_linter_archive_path }}"
  tags:
    - shell
    - shell-linter

- name: Unarchive shellcheck binary
  unarchive:
    src: "{{ shell_linter_archive_path }}"
    dest: "{{ shell_linter_bin_path }}"
    mode: 0755
  tags:
    - shell
    - shell-linter
