---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ 24 * 60 * 60 }}"
  tags:
    - shell

- name: Create shellcheck binaries dir
  file:
    path: "{{ shell_binaries_dir }}/shellcheck"
    state: directory
  become: no
  tags:
    - shell
    - shell-linter

- name: Download shellcheck binary
  get_url:
    url: "{{ shell_linter_url }}"
    dest: "{{ shell_linter_archive_path }}"
  become: no
  tags:
    - shell
    - shell-linter

- name: Unarchive shellcheck binary
  unarchive:
    src: "{{ shell_linter_archive_path }}"
    dest: "{{ shell_binaries_dir }}/shellcheck"
    mode: 0755
  become: no
  tags:
    - shell
    - shell-linter

- name: Link shellcheck binary to path
  file:
    src: "{{ shell_linter_bin_src }}"
    dest: "{{ shell_linter_bin_dest }}"
    mode: 0755
    state: link
  become: yes
  tags:
    - shell
    - shell-linter
