---
shell_binaries_path: "~/binaries"

shell_linter_url: https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz
shell_linter_archive_path: "{{ shell_binaries_path }}/shellcheck.tar.gz"
shell_linter_bin: "/usr/local/bin"
