---
editor_repo_key_url: https://packages.microsoft.com/keys/microsoft.asc
editor_repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

editor_exts:
  - redhat.vscode-yaml
  - shardulm94.trailing-spaces
  - eamodio.gitlens
  - ms-python.python
  - yzhang.markdown-all-in-one
  - DavidAnson.vscode-markdownlint
  # Rust
  # Writing

editor_config_path: ~/.config/Code/User/settings.json
editor_config:
  editor.multiCursorModifier: ctrlCmd
  trailing-spaces.trimOnSave: yes
  editor.formatOnSave: yes
  python.formatting.provider: "black"
  "[python]":
    editor.formatOnPaste: no
