---
editor_repo_key_url: https://packages.microsoft.com/keys/microsoft.asc
editor_repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

editor_exts:
  - redhat.vscode-yaml
  - shardulm94.trailing-spaces
  - eamodio.gitlens
  - ms-python.python
  - yzhang.markdown-all-in-one
  - DavidAnson.vscode-markdownlint
  - dbankier.vscode-quick-select
  # Rust
  # Writing

editor_config_base_separator: "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"
editor_config_path: ~/.config/Code/User/settings.json
editor_config:
  # Traversal
  editor.multiCursorModifier: ctrlCmd
  editor.wordSeparators: "{{ editor_config_base_separator }}"

  # Formatting
  trailing-spaces.trimOnSave: yes
  editor.formatOnSave: yes

  # YAML
  "[yaml]":
    editor.wordSeparators: "{{ editor_config_base_separator }}_"

  # Python
  python.formatting.provider: "black"
  "[python]":
    editor.formatOnPaste: no
