---
- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: "{{ 24 * 60 * 60 }}"
  tags:
    - docker

- name: Install packages required by the docker repo
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present
  tags:
    - docker

- name: Add dockler repo signing key
  apt_key:
    url: "{{ docker_repo_key_url }}"
    state: present
  tags:
    - docker

- name: Add docker repo
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    update_cache: yes
  tags:
    - docker

- name: Install docker
  apt:
    name: "{{ docker_packages }}"
    state: present
  tags:
    - docker

- name: Create docker group
  group:
    name: docker
    state: present
  tags:
    - docker

- name: Add current user to group
  user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: yes
  tags:
    - docker

- name: Run newgrp
  command: newgrp docker
  changed_when: no
  tags:
    - docker
