---
# tasks file for essentials

- name: "Update apt"
  apt: update_cache=yes

- name: "Install essential packages"
  apt:
    name:
      - "build-essential"
      - "libreadline-gplv2-dev"
      - "libncursesw5-dev"
      - "libssl-dev"
      - "libsqlite3-dev"
      - "tk-dev"
      - "libgdbm-dev"
      - "libc6-dev"
      - "libbz2-dev"
      - "libffi-dev"
      - "zlib1g-dev"